title: Makers @ Soc
email: socmakers.gmail.com
author:
  picture: https://avatars3.githubusercontent.com/u/17025450?s=460&v=4 #URL FORMAT
  name: Ten Zhi Yang
  location: Singapore
  description: "Undergraduate helper in Makers @ SoC"
description: "Design. Build. Make "
baseurl: "/"
url: https://tzyinc.github.io
github_username:  tzyinc
github_url: https://github.com/tzyinc

# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
