title: Makers @ SoC
email: socmakers@gmail.com
author:
  picture: https://avatars0.githubusercontent.com/u/33248994?s=400&u=02b18d1c65d042293cd3e93781783a51bd9386b7&v=4 #URL FORMAT
  name: makers-at-soc
  location: Singapore
  description: "Maker lab team"
description: Design. Build. Make
baseurl: "/"
url: https://makers-at-soc.github.io/
github_username:  makers-at-soc
github_url: https://makers-at-soc.github.io/

# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
